spring.application.name=EthQR
server.port=8082

# QR Defaults
qr.payloadFormatIndicator=01
qr.transactionCurrency=230
qr.countryCode=ET

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Payment Service Configuration
payment.token.url=http://192.168.20.45:9001/v1/token
payment.username=bbank
payment.password=bbank1
payment.jwt.assertion=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJCQkFOS0VUQSIsImNlcnRfaXNzIjoiQ049VEVTVCBFVFMgSVBTIElzc3VpbmcgQ0EsIE89RXRoU3dpdGNoLCBDPUVUIiwiY2VydF9zbiI6IjQyMzcxNDE1OTkzMjc0NzI4Mzg3Mjg3NDA5MTkzODAyNTIyMDM0ODA1MTY3OSIsImV4cCI6MTgzNjM3MTMyNywianRpIjoiOTkwNmYyM2EtZmI5MC00MjcyLWJkN2YtY2ViMGY4Y2EwNTI1In0.ap9LX9vY3_vacxqoPoCFdKkHvOe6M0bhuFX9zEV3V2wvp4P7DuzJuOEbMUqBIxOehe5OX2ql3c2-F36ceN-iqNiLkepxBP3mRuaKpIPx9EMoQ0fPuWlXmKko98Wn7jWIXXgGaBuJPM738xtQOkYVqjlVweZv8XcaKgsa82BmRI555NNCBzSMRCY1W6cVr_ILqn5GQnRKr4Zt6VnH7jvBmZf9BaXb4ia2IHbL6rbLm9vNd8omhnFTPECTTLvrkBtQ-BlsiWYyTuB_eFp9gU9Btbi36fffKBRW5-CSCPjq7VDewxVroIdxrz9qDy-Gp56cks4-NkSOLx0QFLtUhobaJw

payment.digest.url=http://192.168.20.49:8080/ips_client_v1/api/digest
payment.incoming.url=http://192.168.20.45:9001/v1/iso20022/incoming
