spring.application.name=EthQR
server.port=8082

# QR Defaults
qr.payloadFormatIndicator=01
qr.transactionCurrency=230
qr.countryCode=ET

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Default Environment Selection
payment.env.default=45

# --- DEFAULT / LEGACY Fallback (Point to .45) ---
payment.token.url=http://192.168.20.45:9001/v1/token
payment.username=bbank
payment.password=bbank1
payment.jwt.assertion=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJCQkFOS0VUQSIsImNlcnRfaXNzIjoiQ049VEVTVCBFVFMgSVBTIElzc3VpbmcgQ0EsIE89RXRoU3dpdGNoLCBDPUVUIiwiY2VydF9zbiI6IjQyMzcxNDE1OTkzMjc0NzI4Mzg3Mjg3NDA5MTkzODAyNTIyMDM0ODA1MTY3OSIsImV4cCI6MTgzNjM3MTMyNywianRpIjoiOTkwNmYyM2EtZmI5MC00MjcyLWJkN2YtY2ViMGY4Y2EwNTI1In0.ap9LX9vY3_vacxqoPoCFdKkHvOe6M0bhuFX9zEV3V2wvp4P7DuzJuOEbMUqBIxOehe5OX2ql3c2-F36ceN-iqNiLkepxBP3mRuaKpIPx9EMoQ0fPuWlXmKko98Wn7jWIXXgGaBuJPM738xtQOkYVqjlVweZv8XcaKgsa82BmRI555NNCBzSMRCY1W6cVr_ILqn5GQnRKr4Zt6VnH7jvBmZf9BaXb4ia2IHbL6rbLm9vNd8omhnFTPECTTLvrkBtQ-BlsiWYyTuB_eFp9gU9Btbi36fffKBRW5-CSCPjq7VDewxVroIdxrz9qDy-Gp56cks4-NkSOLx0QFLtUhobaJw
payment.incoming.url=http://192.168.20.45:9001/v1/iso20022/incoming

# --- Environment 20.45 Configuration ---
payment.45.token.url=http://192.168.20.45:9001/v1/token
payment.45.username=bbank
payment.45.password=bbank1
payment.45.jwt.assertion=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJCQkFOS0VUQSIsImNlcnRfaXNzIjoiQ049VEVTVCBFVFMgSVBTIElzc3VpbmcgQ0EsIE89RXRoU3dpdGNoLCBDPUVUIiwiY2VydF9zbiI6IjQyMzcxNDE1OTkzMjc0NzI4Mzg3Mjg3NDA5MTkzODAyNTIyMDM0ODA1MTY3OSIsImV4cCI6MTgzNjM3MTMyNywianRpIjoiOTkwNmYyM2EtZmI5MC00MjcyLWJkN2YtY2ViMGY4Y2EwNTI1In0.ap9LX9vY3_vacxqoPoCFdKkHvOe6M0bhuFX9zEV3V2wvp4P7DuzJuOEbMUqBIxOehe5OX2ql3c2-F36ceN-iqNiLkepxBP3mRuaKpIPx9EMoQ0fPuWlXmKko98Wn7jWIXXgGaBuJPM738xtQOkYVqjlVweZv8XcaKgsa82BmRI555NNCBzSMRCY1W6cVr_ILqn5GQnRKr4Zt6VnH7jvBmZf9BaXb4ia2IHbL6rbLm9vNd8omhnFTPECTTLvrkBtQ-BlsiWYyTuB_eFp9gU9Btbi36fffKBRW5-CSCPjq7VDewxVroIdxrz9qDy-Gp56cks4-NkSOLx0QFLtUhobaJw
payment.45.incoming.url=http://192.168.20.45:9001/v1/iso20022/incoming
payment.45.bic=BBANKETA

## --- Environment 20.44 Configuration ---
#payment.45.token.url=http://192.168.20.45:9001/v1/token
#payment.45.username=ets_bank
#payment.45.password=ets_bank1
#payment.45.jwt.assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJFVFNFVEFBIiwiY2VydF9pc3MiOiJDTj1URVNUIEVUUyBJUFMgSXNzdWluZyBDQSxPPUV0aFN3aXRjaCxDPUVUIiwiY2VydF9zbiI6IjQyMzcxNDE2MDA3MDExMTI1NzkwNTk5OTAxNDMxNDc1NjY2MjI2Nzc0MDQwOSIsImV4cCI6MTcyNDIyODAxMywianRpIjoiMTEyMjMzMTI0MTIzMjEifQ.VAGu8N9oUHSG6tKzFRMIUfHKV9b5aq3SLiaBKaUa-ZTlyYBV8tKlj4HX-XHZljX_J3Ozi2vuiL7hwy3zrdh4izmZD2WOQ2IdbzfmZt8IsBYlMjOLvOhChc_5TJfBQrRBlujPPTWh7xYWQq4zZ-tWlSky5f5s0jjPpfYWsEe9jIuq5CGw9Tvd02c1mfwB0muaUUIWZI-b0K5qkDpZkSTJk3LOZp_kOarSpL1Hp15Zadm3e2Cd0XLu_kyqvi3hzxTYFfXi54ps06IzazQCQ29tNMVxOBauaICRFfVBDpythLYM3zq6xIY1lQlxUCwCXDL5suOUznNjedTTZE-j_E0xdA
#payment.45.incoming.url=http://192.168.20.45:9001/v1/iso20022/incoming
#payment.45.bic=ETSETAA

# --- Environment 20.44 Configuration ---
payment.44.token.url=http://192.168.20.44:9001/v1/token
payment.44.username=ets_bank
payment.44.password=ets_bank1
payment.44.jwt.assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJFVFNFVEFBIiwiY2VydF9pc3MiOiJDTj1URVNUIEVUUyBJUFMgSXNzdWluZyBDQSxPPUV0aFN3aXRjaCxDPUVUIiwiY2VydF9zbiI6IjQyMzcxNDE1OTE2OTU1ODcxNTg1NTUzODE2ODIwNzEyNDIyMjc3OTA2NDM5NiIsImV4cCI6MTczMDIwOTU3NiwianRpIjoiMTEyMjMzMTI0MTIzMjEifQ.rE4JMzEEc8AVOGQ1boKArBoKfb2j0AtDna99aClbYv8w8YYIVTUYQSY6fIZrM7ELvyixNVtPY2eBYIXVcDwIeK4IJkk5l9FKBBk-69VPcTn0GPcTXKMdDiAUBk0_PX5TaC8Vb1kLSOJ3FL2g-Ma0m4QiFmETSnsr5nShaTQdDVvZDE5uWQ166YnYu7L6knbJpfRiFjD84CkDczgX74z8fVE38Va2Lh3Awmo9hKs8QM1yLTMDpYBa6-aFPUlVdsMAzn91XgD5DC13vGNehO5pNVYYK0CbjXwy3_aB33GJzBSAs4LQaEJr2gFIFZ4ypMvUN5qAuihCEzHUe_2C_h4Tiw
payment.44.incoming.url=http://192.168.20.44:9001/v1/iso20022/incoming
payment.44.bic=ETSETAA

# Shared Configuration
payment.digest.url=http://192.168.20.49:8080/ips_client_v1/api/digest
#payment.digest.url=http://192.168.20.46:8282/axum/api/digest
